### ISSUE TITLE
Upgrading to 1.21 does not work

### ISSUE THREAD

**Issue by Aegrithas** [xanthian/copperandtuffbackport#1] opened 2024-09-06 18:36 UTC
If I make a world with this mod (I only tested on 1.20.1, but I assume the behavior is the same), place some of the backported blocks, and then upgrade the world to vanilla 1.21, then the blocks disappear. I assume this is because they are registered with the namespace `copperandtuffbackport` rather than `minecraft`.

**Comment by xanthian** [comment] 2024-09-07 18:50
correct.
not a bug, so wont be fixing i'm afraid.

**Closed as completed by xanthian** 2024-09-07 18:50 UTC
